apiVersion: v1
kind: Service
metadata:
  name: flarie-todo-service
spec:
  type: NodePort
  selector:
    app: flarie-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32767
