name: Terraform

on:
  push:
    branches:
      - flarie-iac  # This will trigger the workflow on every push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Checkout the repository to access your Terraform configuration files
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Terraform environment
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # Set environment variables for DigitalOcean Spaces credentials
    - name: Set environment variables for DigitalOcean Spaces credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.DOS_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DOS_SECRET_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=nyc3" >> $GITHUB_ENV  # Set the region to match your DigitalOcean Space region

    # Initialize Terraform to set up the backend and provider configurations
    - name: Terraform Init
      run: terraform init

    # Apply the Terraform plan to create the resources
    - name: Terraform Apply
      run: terraform apply -auto-approve
